### ISSUE TITLE
I use peload, perun, peunload commands and nothing happens. The exe virus I generated with cobaltstrike is not powershell, and this is the result of my tests on both windows and linux clients.

### ISSUE THREAD

**Issue by kasjhkjaSD** [Octoberfest7/Inline-Execute-PE#1]
![image](https://user-images.githubusercontent.com/67731867/222060715-b9e7d4e5-cb1d-4f13-b8ce-5732a3677a83.png)

**Comment by Octoberfest7** [comment]
If you open the script console and try running the commands are there any messages?

Also I only built the tool to work on Linux as far as the paths the .cna script looks for and uses so it would have to be modified to work on windows

**Comment by kasjhkjaSD** [comment]
> If you open the script console and try running the commands are there any messages?
> 
> Also I only built the tool to work on Linux as far as the paths the .cna script looks for and uses so it would have to be modified to work on windows

I got this problem:
![image](https://user-images.githubusercontent.com/67731867/222063153-052b6128-e0f7-435c-8e91-99a8faa9fd0f.png)

**Comment by Octoberfest7** [comment]
So first off try all this on a Linux machine as that is what I made this for. Second, if you reload the .cna and use peload e.g. peload /my/windows/binary, do you get that same error you just posted? That error was in the peunload section of code, so I want to see if you get anything using peload.

**Comment by kasjhkjaSD** [comment]
> So first off try all this on a Linux machine as that is what I made this for. Second, if you reload the .cna and use peload e.g. peload /my/windows/binary, do you get that same error you just posted? That error was in the peunload section of code, so I want to see if you get anything using peload.

I reloaded the cna script on kali and encountered such a problem：
![image](https://user-images.githubusercontent.com/67731867/222070551-70ea1016-4a7e-4687-b0f1-272cd161a3fa.png)
![image](https://user-images.githubusercontent.com/67731867/222070586-d03b9b1a-6e54-478e-a6dc-13f1d6ec5f16.png)

**Comment by Octoberfest7** [comment]
Are you using the precompiled BOFs in the repo or did you run make to recompile them? If you haven't, recompile them.

Are you running cobaltstrike 4.4 as your directory suggested? An old version of cobaltstrike could have some kind of confliction too im not sure

**Comment by kasjhkjaSD** [comment]
I recompiled these files, and my cobaltstrike version is 4.4, but this error still occurs.
![image](https://user-images.githubusercontent.com/67731867/222076456-01729043-c7b6-4e1c-a546-908cc822e0dd.png)
![image](https://user-images.githubusercontent.com/67731867/222076818-25311c46-4462-43f8-8182-1538edb8beb0.png)

**Comment by Octoberfest7** [comment]
Id suggest updating to the latest version of cobaltstrike. Given the lack of others having this issue with this project this seems the most likely culprit.

**Comment by kasjhkjaSD** [comment]
> Id suggest updating to the latest version of cobaltstrike. Given the lack of others having this issue with this project this seems the most likely culprit.

I use cobalstrike4.7, and there are still many problems with this tool. For example, if I use perun and peunload, my session will be disconnected directly.
![image](https://user-images.githubusercontent.com/67731867/222383011-dddeab09-39a5-4d11-b294-002ca3e6d9a3.png)
Script console doesn't have any info
![image](https://user-images.githubusercontent.com/67731867/222383113-3af0c985-0071-46dd-b4bc-20a89a8b5585.png)

**Comment by Octoberfest7** [comment]
> > Id suggest updating to the latest version of cobaltstrike. Given the lack of others having this issue with this project this seems the most likely culprit.
> 
> I use cobalstrike4.7, and there are still many problems with this tool. For example, if I use perun and peunload, my session will be disconnected directly. ![image](https://user-images.githubusercontent.com/67731867/222383011-dddeab09-39a5-4d11-b294-002ca3e6d9a3.png) Script console doesn't have any info ![image](https://user-images.githubusercontent.com/67731867/222383113-3af0c985-0071-46dd-b4bc-20a89a8b5585.png)

Cobaltstrike is telling you what is wrong if you read the error. You need to increase the max task size in the profile. Look at the cs documentation online for the max size setting in the profile, change it in the profile, restart TS, generate new beacons, and try again
